# Generated by Django 4.2.7 on 2023-11-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0003_menuitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
